[package]
name = "cnv"
version = "0.1.0"
edition = "2021"
authors = ["eeraj <neerrrajj@proton.me>"]
description = "Command-line tool for converting units of measurement."
license = "MIT"
repository = "https://github.com/neerrrajj/cnv"
readme = "README.md"

[dependencies]
once_cell = "1.20.3"
